# Generated by Django 5.1.1 on 2024-10-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='intro',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
