# Generated by Django 5.0.6 on 2024-07-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('intro', models.TextField()),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
